# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb8bce064d093f3257ad6cb7f865b5c9f7037dbde914614a8ce5e34f6bcbb13b95434df7d8bfbc0210e920d7f43ac6a4665b36c8394f636d0b6412c9b53c0ff3

test:
  secret_key_base: 014907486f88b6984fd288cb0715729455f8a36edad00bacf9aab430ed904aa17ee09c9c3c636bd6bd05524f1a1327ffca37e7a5690262c81b9dc9a8cffb8d5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
